---

- name: Install apt_repo_required_packages
  apt:
    name: "{{ apt_repo_required_packages }}"
    state: present

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  when: apt_repo_enable_apt_transport_https

- name: Add keys for repositories
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ apt_repo_keys_to_add }}"

- name: Add apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repo_to_add }}"
  # PPA somtimes returns HTTP 503
  retries: 6
  delay: 10
