---

galaxy_info:
  author: idealista
  company: Idealista S.A.U.
  description: Promscale Role
  min_ansible_version: 2.9.9
  license: Apache 2.0
  galaxy-tags:
    - promscale
    - prometheus
    - timescaledb
  platforms:
    - name: Debian
      versions:
        - buster
