---
driver:
  name: vagrant

transport:
  name: rsync

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 1
  ansible_verbose: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  http_proxy: <%= ENV['ANSIBLE_PROXY'] %>
  idempotency_test: true
  additional_copy_path:
    - extra_modules
    - filter_plugins
    - extra_roles

platforms:
  - name: ubuntu-16.04-amd64
    driver:
      box: trombik/ansible-ubuntu-16.04-amd64
      box_check_update: false

  - name: ubuntu-18.04-amd64
    driver:
      box: trombik/ansible-ubuntu-18.04-amd64
      box_check_update: false

  - name: ubuntu-20.04-amd64
    driver:
      box: trombik/ansible-ubuntu-20.04-amd64
      box_check_update: false

  - name: devuan-3-amd64
    driver:
      box: trombik/ansible-devuan-3-amd64
      box_check_update: false

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: tests/serverspec/default.yml
    verifier:
      name: shell
      command: rspec -c -f d -I tests/serverspec tests/serverspec/default_spec.rb
