---
- name: TIMESCALEDB | Add .pgpass file
  template:
    src: "{{ timescaledb_multinode_pgpass_template_file }}"
    dest: "{{ timescaledb_multinode_pgpass_path }}/.pgpass"
    owner: "{{ timescaledb_pg_user }}"
    group: "{{ timescaledb_pg_group }}"
    mode: 0600
