---
galaxy_info:
  company: Idealista S.A.U
  author: idealista
  description: postgreSQL role
  min_ansible_version: 2.9.2
  license: Apache 2.0
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
    - name: EL
      versions:
        - 7
        - 8
