---
galaxy_info:
  author: Tomoyuki Sakurai
  role_name: ntopng
  description: ansible role for ntopng
  company: N/A
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: FreeBSD
      versions:
        - 11.3
        - 12.0
    - name: OpenBSD
      versions:
        - 6.4
    - name: Ubuntu
      versions:
        - bionic
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - ntop
    - ntopng
dependencies: []
