---
# This is an example playbook to execute goss tests.
# Tests need distributed to the appropriate ansible host/groups
# prior to execution by `goss validate`.

- name: Verify
  hosts: all
  become: true
  vars:
    goss_version: v0.3.13
    goss_arch: amd64
    goss_sha256sum: eb3522ff9682736ff61e2ad114de227de98debcf8a03ca66fcda3917577313e0
    goss_dst: /usr/local/bin/goss
    goss_url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
    goss_test_directory: /tmp
    goss_format: documentation
  vars_files:
    - pg_vars.yml
    - "../../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

  tasks:
    - name: PostgreSQL | Setting OS specific variables
      set_fact:
        pg_packages: "{{ pg_packages if pg_packages is defined else __pg_packages }}"
        pg_config_directory: "{{ pg_config_directory if pg_config_directory is defined else __pg_config_directory }}"
        pg_data_directory: "{{ pg_data_directory if pg_data_directory is defined else __pg_data_directory }}"
        pg_log_directory: "{{ pg_log_directory if pg_log_directory is defined else __pg_log_directory }}"

    - name: Download and install Goss
      get_url:
        url: "{{ goss_url }}"
        dest: "{{ goss_dst }}"
        mode: 0755
        sha256sum: "{{ goss_sha256sum }}"
      register: download_goss
      until: download_goss is succeeded
      retries: 3

    - name: Copy Goss tests to remote
      template:
        src: "{{ item }}"
        dest: "{{ goss_test_directory }}/{{ item | basename }}"
      with_fileglob:
        - "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/test_*.yml"

    - name: Register test files
      shell: "ls {{ goss_test_directory }}/test_*.yml"
      register: test_files

    - name: Execute Goss tests
      command: "{{ goss_dst }} -g {{ item }} validate --format {{ goss_format }}"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"

    - name: Display details about the Goss results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Goss failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"
